name: Security Checks

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  security:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm ci

    - name: Install test tools (optional if nyc not found)
      run: npm install --save-dev nyc

    - name: Run server tests
      run: npm run test:server

    - name: Copy API test coverage data
      run: cp build/reports/coverage/api-tests/lcov.info api-lcov.info || true

    - name: Copy unit test coverage data
      run: cp build/reports/coverage/frontend-tests/lcov.info frontend-lcov.info || true

    - name: Run Syft
      uses: anchore/sbom-action@v0.15.3
      with:
        output-file: sbom.syft.json
        format: json
      continue-on-error: true

    - name: Run Semgrep
      uses: returntocorp/semgrep-action@v1
      with:
        config: "p/default"
      continue-on-error: true

    - name: Run Gitleaks
      uses: gitleaks/gitleaks-action@v2
      with:
        config-path: .gitleaks.toml
      continue-on-error: true

    - name: Start Juice Shop App
      run: docker-compose up -d

    - name: Run OWASP ZAP scan
      uses: zaproxy/action-baseline@v0.7.0
      with:
        target: 'http://localhost:3000'
      continue-on-error: true

